### ISSUE TITLE
Incorrect default for AllocationManager.listAllocations allocationScope

### ISSUE THREAD

**Issue by btgoodwin** [RedhawkSDR/redhawk#20]
If you access the allocation manager from the python shell and call `listAllocations()`, you receive the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/redhawk-sdr/core/lib/python/ossie/utils/redhawk/core.py", line 1245, in listAllocations
    retval = self.ref.listAllocations( allocationScope, count )
  File "/usr/redhawk-sdr/core/lib/python/ossie/cf/cf_idl.py", line 1587, in listAllocations
    return self._obj.invoke("listAllocations", _0_CF.AllocationManager._d_listAllocations, args)
omniORB.CORBA.BAD_PARAM: CORBA.BAD_PARAM(omniORB.BAD_PARAM_WrongPythonType, CORBA.COMPLETED_NO, ["Expecting enum 'AllocationScopeType' item, got ALL_DEVICES", "Operation 'listAllocations' parameter 0"])
```

Steps to reproduce (with a running Domain):

```
from ossie.utils import redhawk
dom = redhawk.attach()
dom.allocationMgr.listAllocations()
```

The `help()` for this method indicates it has a default value for the related parameter, however it's set to `ALL_DEVICES` rather than `ALL_ALLOCATIONS` (which is in the class scope already, and produces the expected result):

```
from ossie.utils import redhawk
from ossie.utils.redhawk.core import AllocationManager
dom = redhawk.attach()
dom.allocationMgr.listAllocations(AllocationManager.ALL_ALLOCATIONS)
([], <ossie.utils.redhawk.model.IteratorContainer object at 0x7f9c57a790>)
```

**Comment by RedhawkDeployer** [comment]
We have confirmed the issue and have put the issue on our backlog for scheduling.

**Comment by shmahon** [comment]
The fix for this issue will be published with the imminent RH2.2.6 release.
