### ISSUE TITLE
RH v3.0.0 - Failed to fetch profile object from profile path: 'sca:///domain/DomainManager.dmd.xml

### ISSUE THREAD

**Issue by navarrothiago** [RedhawkSDR/redhawk#52]
I have faced this error using the v3.0.0 after trying to connect the DeviceManger. The message is shown inside REDHAWK_DEV CONNECTED.  Am I missing anything? 
```
Failed to fetch profile object from profile path: 'sca:///domain/DomainManager.dmd.xml?domain=REDHAWK_DEV&fs=IOR%3A000000000000001749444C3A43462F46696C654D616E616765723A312E30000000000001000000000000007401010200100000003139322E3136382E3132322E3132330087C200001C000000FF446F6D61696E4D616E61676572FE00170A6301000C5E00000000000200000000000000080000000100000000545441010000001C00000001000000010001000100000001000105090101000100000009010100#/'
```

```
rg.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: org.eclipse.core.runtime.CoreException: File cache error: /home/rds/workspace/.metadata/.plugins/gov.redhawk.sca.efs/fileCache/sdr_REDHAWK_DEV/dom/domain/DomainManager.dmd.xml
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(ResourceSetImpl.java:406)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:220)
	at gov.redhawk.model.sca.ProfileObjectWrapper$Util.fetchProfileObject(ProfileObjectWrapper.java:225)
	at gov.redhawk.model.sca.impl.ScaPropertyContainerImpl.fetchProfileObject(ScaPropertyContainerImpl.java:379)
	at gov.redhawk.model.sca.impl.ScaPropertyContainerImpl.fetchPropertyDefinitions(ScaPropertyContainerImpl.java:708)
	at gov.redhawk.model.sca.impl.ScaPropertyContainerImpl.fetchProperties(ScaPropertyContainerImpl.java:611)
	at gov.redhawk.model.sca.impl.ScaDomainManagerImpl.fetchAttributes(ScaDomainManagerImpl.java:2187)
	at gov.redhawk.model.sca.impl.CorbaObjWrapperImpl.refresh(CorbaObjWrapperImpl.java:761)
	at gov.redhawk.sca.model.provider.refresh.internal.RefresherSwitch$1.refresh(RefresherSwitch.java:90)
	at gov.redhawk.sca.model.provider.refresh.internal.RefresherSwitch$1.refresh(RefresherSwitch.java:84)
	at gov.redhawk.sca.model.provider.refresh.internal.RefreshTasker.refresh(RefreshTasker.java:264)
	at gov.redhawk.sca.model.provider.refresh.internal.RefreshTasker$RefreshTask.run(RefreshTasker.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.eclipse.core.runtime.CoreException: File cache error: /home/rds/workspace/.metadata/.plugins/gov.redhawk.sca.efs/fileCache/sdr_REDHAWK_DEV/dom/domain/DomainManager.dmd.xml
	at gov.redhawk.efs.sca.internal.cache.FileCache.downloadFile(FileCache.java:159)
	at gov.redhawk.efs.sca.internal.cache.FileCache.update(FileCache.java:74)
	at gov.redhawk.efs.sca.internal.cache.FileCache.openInputStream(FileCache.java:84)
	at gov.redhawk.efs.sca.internal.ScaFileStore.openInputStream(ScaFileStore.java:306)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.emf.ecore.resource.impl.EFSURIHandlerImpl.createInputStream(EFSURIHandlerImpl.java:249)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:360)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1314)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	... 19 more
Caused by: java.util.concurrent.ExecutionException: org.omg.CORBA.MARSHAL: Server-side Exception: null  vmcid: 0x41540000  minor code: 10  completed: No
	at mil.jpeojtrs.sca.util.ProtectedThreadExecutor.submit(ProtectedThreadExecutor.java:86)
	at gov.redhawk.efs.sca.internal.cache.FileCache.readProtected(FileCache.java:199)
	at gov.redhawk.efs.sca.internal.cache.FileCache.copyLarge(FileCache.java:187)
	at gov.redhawk.efs.sca.internal.cache.FileCache.downloadFile(FileCache.java:137)
	... 30 more
Caused by: org.omg.CORBA.MARSHAL: Server-side Exception: null  vmcid: 0x41540000  minor code: 10  completed: No
	at sun.reflect.GeneratedConstructorAccessor26.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jacorb.orb.SystemExceptionHelper.read(SystemExceptionHelper.java:222)
	at org.jacorb.orb.ReplyReceiver.getReply(ReplyReceiver.java:456)
	at org.jacorb.orb.Delegate._invoke_internal(Delegate.java:1419)
	at org.jacorb.orb.Delegate.invoke_internal(Delegate.java:1188)
	at org.jacorb.orb.Delegate.invoke(Delegate.java:1176)
	at org.omg.CORBA.portable.ObjectImpl._invoke(ObjectImpl.java:475)
	at CF._FileStub.read(_FileStub.java:66)
	at gov.redhawk.efs.sca.internal.ScaFileInputStream.read(ScaFileInputStream.java:84)
	at java.io.InputStream.read(InputStream.java:101)
	at gov.redhawk.efs.sca.internal.cache.FileCache$1.call(FileCache.java:203)
	at gov.redhawk.efs.sca.internal.cache.FileCache$1.call(FileCache.java:1)
	at mil.jpeojtrs.sca.util.ProtectedThreadExecutor.submit(ProtectedThreadExecutor.java:84)
```

**Comment by navarrothiago** [comment]
It seems that the issue was fixed in v3.0.1 - https://github.com/RedhawkSDR/redhawk/releases/tag/3.0.1.

> The effort in REDHAWK 3.0.1 focused on:
> - Replace log4j with reload4j in the Core Framework and in the IDE.
> - Resolved bug preventing fei3-generator from generating python code
> - **Resolved bug preventing IDE from connecting to a running redhawk-3.0.0 domain**
